# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "burnnote"
friendly_name1: Burn After Reading
friendlyName2: Self Destructing Messages
default_local:  0
behind_proxy: 0


# Available options for how many times a message can be read. These will be
# displayed in a dropdown list when creating the message.  The values will be
# listed in order from lowest to highest, regardless of how they are ordered
# here, however the first number in this list will be the default selection.
read_limits:
    - 2
    - 1
    - 10
    - 5
    #- unlimited

# Enable unlimted read requests within the time period.  This will always be
# listed last. Use 1 and 0 for true / false (especially false).
unlimited_reads: 1

# Expiration periods available (in hours).  They will display in a dropdown 
# list from lowest to highest, but the first value listed will be the 
# default selected.
expirations:
    - 24
    - 48
    - 2
    - 96
    - 720

# The default layout to use for your application (located in
# views/layouts/main.tt)
#layout: "main"
layout: bootstrap

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

#template: "simple"

template: "template_toolkit"
engines:
  template:
    template_toolkit:
      start_tag: '<%'
      end_tag:   '%>'

# session engine
#
# Simple: in-memory session store - Dancer2::Session::Simple
# YAML: session stored in YAML files - Dancer2::Session::YAML
#
# Check out metacpan for other session storage options:
# https://metacpan.org/search?q=Dancer2%3A%3ASession&search_type=modules
#
# Default value for 'cookie_name' is 'dancer.session'. If you run multiple
# Dancer apps on the same host then you will need to make sure 'cookie_name'
# is different for each app.
#
#engines:
#  session:
#    Simple:
#      cookie_name: testapp.session
#
#engines:
#  session:
#    YAML:
#      cookie_name: eshop.session
#      is_secure: 1
#      is_http_only: 1

plugins:
    Ajax:
        content_type: 'application/json'
