# configuration file for production environment

# only log warning and error messsages
log: "core"

# log message to a file in logs/
logger: "file"
logger: "file"
engines:
  logger:
    File:
      log_dir: '/usr/home/burnnote/www/burnnote/logs'
      file_name: burnnote.log


# don't consider warnings critical
warnings: 0

# hide errors
show_errors: 0

# disable server tokens in production environments
no_server_tokens: 1
